name: 'Setup Cairo Native Dependencies'
description: 'Sets up LLVM and GMP libraries'

runs:
  using: "composite"
  steps:
   - name: add llvm deb repository
     uses: myci-actions/add-deb-repo@10
     with:
       repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
       repo-name: llvm-repo
       keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
   - name: Install LLVM
     run: sudo apt-get install llvm-17 llvm-17-dev llvm-17-runtime clang-17 clang-tools-17 lld-17 libpolly-17-dev libmlir-17-dev mlir-17-tools
     shell: bash
   - name: Install gmplib
     run: sudo apt install -y libgmp3-dev
     shell: bash
