name: CI

on:
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited

jobs:
  commitlint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request' && !(contains(github.event.pull_request.title, '/merge-main') || contains(github.event.pull_request.title, '/merge main'))
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Validate PR title with commitlint
        if: github.event_name != 'merge_group' && github.event_name != 'push' && !(contains(github.event.pull_request.title, '/merge-main') || contains(github.event.pull_request.title, '/merge main'))
        run: echo "${{ github.event.pull_request.title }}" | commitlint --verbose

  format:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-12
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  clippy:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-dep-macos
        id: native-deps
      - run: scripts/clippy.sh
        env:
          CAIRO_NATIVE_RUNTIME_LIBRARY: ${{ steps.native-deps.outputs.cairo-native-runtime-library }}
          MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
          LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
          TABLEGEN_180_PREFIX: /usr/lib/llvm-18/

  run-python-tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
      - run: pytest scripts/merge_paths_test.py

  run-tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-dep-macos
        id: native-deps
      - run: cd ./cairo_native; source ./env-macos.sh; cd ..; cargo test --package blockifier --features testing --test erc20_tests -- should_deploy --exact --show-output

  run-concurrency-tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-dep-macos
        id: native-deps
      - run: cargo test --features concurrency
        env:
          CAIRO_NATIVE_RUNTIME_LIBRARY: ${{ steps.native-deps.outputs.cairo-native-runtime-library }}
          MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
          LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
          TABLEGEN_180_PREFIX: /usr/lib/llvm-18/

  udeps:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        name: "Rust Toolchain Setup"
        with:
          toolchain: nightly-2023-12-21
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-dep-macos
      - uses: Swatinem/rust-cache@v2
        id: "cache-cargo"
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: |
          wget -O - -c https://github.com/est31/cargo-udeps/releases/download/v0.1.45/cargo-udeps-v0.1.45-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          cargo-udeps-*/cargo-udeps udeps
        env:
          RUSTUP_TOOLCHAIN: nightly-2023-12-21
          MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
          LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
          TABLEGEN_180_PREFIX: /usr/lib/llvm-18/
