name: ERC20 Native Tests

on:
  pull_request:

jobs:
  erc20-native-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install llvm
        run: sudo apt-get update && sudo apt-get install -y llvm-17
      - uses: actions/checkout@v3
        with:
          repository: 'NethermindEth/cairo_native'
          ref: 'execution_info_v2_update'
          path: 'cairo_native'
      - name: Build cairo_native runtime
        run: |
          cd cairo_native/runtime
          cargo build --release
      - name: Set env vars
        run: |
          echo "MLIR_SYS_170_PREFIX=/usr/lib/llvm-17" >> $GITHUB_ENV
          echo "LLVM_SYS_170_PREFIX=/usr/lib/llvm-17" >> $GITHUB_ENV
          echo "TABLEGEN_170_PREFIX=/usr/lib/llvm-17" >> $GITHUB_ENV
          echo "CAIRO_NATIVE_RUNTIME_LIBDIR=$(pwd)/cairo_native/runtime/target/release" >> $GITHUB_ENV
      - name: Run ERC20 Native Tests
        run: cd crates/blockifier && cargo test --test erc20_tests --features testing