name: ERC20 Native Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  erc20-native-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: add llvm deb repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: sudo apt-get install llvm-17 llvm-17-dev llvm-17-runtime clang-17 clang-tools-17 lld-17 libpolly-17-dev libmlir-17-dev mlir-17-tools
      - name: Install gmplib
        run: sudo apt install -y libgmp3-dev
      - uses: actions/checkout@v3
        with:
          repository: 'lambdaclass/cairo_native'
          ref: "main"
          path: 'cairo_native'
      - name: Run ERC20 Native Tests
        run: cd ./cairo_native/runtime && cargo build --release && cd ../.. && echo $CAIRO_NATIVE_RUNTIME_LIBDIR && ls $CAIRO_NATIVE_RUNTIME_LIBDIR && cd crates/blockifier && cargo test --test erc20_tests --features testing
        env:
          MLIR_SYS_170_PREFIX: /usr/lib/llvm-17
          LLVM_SYS_170_PREFIX: /usr/lib/llvm-17
          TABLEGEN_170_PREFIX: /usr/lib/llvm-17
          CAIRO_NATIVE_RUNTIME_LIBDIR: {{ workflow.workspace }}/cairo_native/runtime/target/release