name: ERC20 Native Tests

on:
  pull_request:

jobs:
  erc20-native-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install llvm
        run: sudo apt-get update && sudo apt-get install libllvm-17-ocaml-dev libllvm17 llvm-17 llvm-17-dev llvm-17-doc llvm-17-examples llvm-17-runtime
      - name: Install gmplib
        run: sudo apt install -y libgmp3-dev
      - uses: actions/checkout@v3
        with:
          repository: 'lambdaclass/cairo_native'
          ref: "main"
          path: 'cairo_native'
      - name: Build cairo_native runtime
        run: |
          cd cairo_native/runtime
          cargo build --release
      - name: Run ERC20 Native Tests
        run: cd crates/blockifier && cargo test --test erc20_tests --features testing
        env:
          MLIR_SYS_170_PREFIX: /usr/lib/llvm-17
          LLVM_SYS_170_PREFIX: /usr/lib/llvm-17
          TABLEGEN_170_PREFIX: /usr/lib/llvm-17
          CAIRO_NATIVE_RUNTIME_LIBDIR: $(pwd)/cairo_native/runtime/target/release
